### ==========================================
### 1. ADMIN API (ระบบผู้ดูแลระบบ)
### ==========================================

### 1 Login (แอดมิน)
POST http://localhost:9091/admin/login
Content-Type: application/json

{
    "email": "cchuewongdee08@gmail.com",
    "password": "Kokoku254808au302",
    "rememberMe": false
}

### 2 Register / Signup (สมัครสมาชิกแอดมิน)
POST http://localhost:9091/admin/register-admin
Content-Type: application/json
{
    "username": "chaiyapat2",
    "email": "cchuewongdee08@gmail.com",
    "password": "kokoku254808au302",
    "firstname": "Chaiyapat",
    "lastname": "chuewongdee"
}

### 3 Forgot Password (ลืมรหัสผ่านแอดมิน)
POST http://localhost:9091/admin/forgot-password
Content-Type: application/json

{
    "email": "cchuewongdee08@gmail.com"
}

### 4 Profile (ดูข้อมูลส่วนตัวแอดมิน)
# 1. รัน Admin Login (1) ก่อน เพื่อรับ token ใหม่
# 2. นำ token มาวางแทน <your-admin-jwt-token> ด้านล่าง
GET http://localhost:9091/admin/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg4MjcyNDY1LCJleHAiOjE3OTA4NjQ0NjV9.MMQWxgJ-ODagvuE-css8qfuJI6lLeseHAJGMXCmVMow


### ==========================================
### 2. USER API (ระบบสมาชิก)
### ==========================================

### 5 User Login (เข้าสู่ระบบสมาชิก)
POST http://localhost:9091/api/auth/local
Content-Type: application/json

{
    "identifier": "chaiyapat8@gmail.com",
    "password": "Kokoku254808"
}

### 6 User Register / Signup (สมัครสมาชิก)
POST http://localhost:9091/api/auth/local/register
Content-Type: application/json

{
    "username": "chaiyapat9",
    "email": "chaiyapat9@gmail.com",
    "password": "Kokoku254808"
}

### 7 User Forgot Password (ลืมรหัสผ่านสมาชิก)
POST http://localhost:9091/api/auth/forgot-password
Content-Type: application/json

{
    "email": "chaiyapat8@gmail.com"
}

### 8 User Profile (ข้อมูลส่วนตัวสมาชิก)
# 1. รัน User Login (5) ก่อน เพื่อรับ jwt ใหม่
# 2. นำ jwt มาวางแทน <your-user-jwt-token> ด้านล่าง
GET http://localhost:9091/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsImlhdCI6MTc4ODI3Mjc3NSwiZXhwIjoxNzkwODY0Nzc1fQ.a4YA_L7y5N6DEfqC9qE2xSvA5ipB67Gf4ilFj6_bGwk